# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .asset import Asset
    from .create_asset_device import CreateAssetDevice
    from .create_asset_request import CreateAssetRequest
    from .create_asset_response import CreateAssetResponse
    from .create_asset_status import CreateAssetStatus
    from .create_findings_error import CreateFindingsError
    from .create_findings_request import CreateFindingsRequest
    from .create_findings_response import CreateFindingsResponse
    from .get_scan_activities_response import GetScanActivitiesResponse
    from .get_scan_activity_response import GetScanActivityResponse
    from .get_scan_status_response import GetScanStatusResponse
    from .nucleus_finding_state import NucleusFindingState
    from .provider_specific_finding_state import ProviderSpecificFindingState, ProviderSpecificFindingState_Nucleus
    from .query_assets_response import QueryAssetsResponse
    from .query_findings_response import QueryFindingsResponse
    from .query_scans_response import QueryScansResponse
    from .scan_configuration import ScanConfiguration
    from .scan_frequency_option import ScanFrequencyOption
    from .scan_schedule import ScanSchedule
    from .scan_status import ScanStatus
    from .security_finding import SecurityFinding
    from .update_finding_request import UpdateFindingRequest
    from .upload_scan_request import UploadScanRequest
    from .upload_scan_response import UploadScanResponse
    from .upload_scan_status import UploadScanStatus
    from .user import User
    from .vulnerabilities_finding import VulnerabilitiesFinding
    from .vulnerabilities_query_scan_findings_response import VulnerabilitiesQueryScanFindingsResponse
    from .vulnerability_severity_filter_value import VulnerabilitySeverityFilterValue
    from .vulnerability_state_filter_value import VulnerabilityStateFilterValue
_dynamic_imports: typing.Dict[str, str] = {
    "Asset": ".asset",
    "CreateAssetDevice": ".create_asset_device",
    "CreateAssetRequest": ".create_asset_request",
    "CreateAssetResponse": ".create_asset_response",
    "CreateAssetStatus": ".create_asset_status",
    "CreateFindingsError": ".create_findings_error",
    "CreateFindingsRequest": ".create_findings_request",
    "CreateFindingsResponse": ".create_findings_response",
    "GetScanActivitiesResponse": ".get_scan_activities_response",
    "GetScanActivityResponse": ".get_scan_activity_response",
    "GetScanStatusResponse": ".get_scan_status_response",
    "NucleusFindingState": ".nucleus_finding_state",
    "ProviderSpecificFindingState": ".provider_specific_finding_state",
    "ProviderSpecificFindingState_Nucleus": ".provider_specific_finding_state",
    "QueryAssetsResponse": ".query_assets_response",
    "QueryFindingsResponse": ".query_findings_response",
    "QueryScansResponse": ".query_scans_response",
    "ScanConfiguration": ".scan_configuration",
    "ScanFrequencyOption": ".scan_frequency_option",
    "ScanSchedule": ".scan_schedule",
    "ScanStatus": ".scan_status",
    "SecurityFinding": ".security_finding",
    "UpdateFindingRequest": ".update_finding_request",
    "UploadScanRequest": ".upload_scan_request",
    "UploadScanResponse": ".upload_scan_response",
    "UploadScanStatus": ".upload_scan_status",
    "User": ".user",
    "VulnerabilitiesFinding": ".vulnerabilities_finding",
    "VulnerabilitiesQueryScanFindingsResponse": ".vulnerabilities_query_scan_findings_response",
    "VulnerabilitySeverityFilterValue": ".vulnerability_severity_filter_value",
    "VulnerabilityStateFilterValue": ".vulnerability_state_filter_value",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Asset",
    "CreateAssetDevice",
    "CreateAssetRequest",
    "CreateAssetResponse",
    "CreateAssetStatus",
    "CreateFindingsError",
    "CreateFindingsRequest",
    "CreateFindingsResponse",
    "GetScanActivitiesResponse",
    "GetScanActivityResponse",
    "GetScanStatusResponse",
    "NucleusFindingState",
    "ProviderSpecificFindingState",
    "ProviderSpecificFindingState_Nucleus",
    "QueryAssetsResponse",
    "QueryFindingsResponse",
    "QueryScansResponse",
    "ScanConfiguration",
    "ScanFrequencyOption",
    "ScanSchedule",
    "ScanStatus",
    "SecurityFinding",
    "UpdateFindingRequest",
    "UploadScanRequest",
    "UploadScanResponse",
    "UploadScanStatus",
    "User",
    "VulnerabilitiesFinding",
    "VulnerabilitiesQueryScanFindingsResponse",
    "VulnerabilitySeverityFilterValue",
    "VulnerabilityStateFilterValue",
]
