# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .asset import Asset


class CreateAssetRequest(UncheckedBaseModel):
    asset: Asset = pydantic.Field()
    """
    Asset to create in the vulnerability scanning system.
    """

    source_name: str = pydantic.Field()
    """
    Name of the source that created the asset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
