# This file was auto-generated by Fern from our API Definition.

TypeUid = int
"""
TypeUid is an enum, and the following values are allowed.
200400 - Unknown
200401 - Create: A finding was created.
200402 - Update: A finding was updated.
200403 - Close: A finding was closed.
200499 - Other
"""
