# This file was auto-generated by Fern from our API Definition.

Timestamp = int
"""
The timestamp format is the number of milliseconds since the Epoch 01/01/1970 00:00:00 UTC. For example:<br><code>1618524549901</code>.
"""
