# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...common.types.id import Id
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class OptionValue(UncheckedBaseModel):
    """
    Represents a possible option from a set of choices, such as an enum value. The choices may have separate display names and IDs.
    """

    id: Id
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
