# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAssetsClient, RawAssetsClient
from .types.create_device_response import CreateDeviceResponse
from .types.create_devices_response import CreateDevicesResponse
from .types.create_software_inventory_response import CreateSoftwareInventoryResponse
from .types.device import Device
from .types.get_labels_response import GetLabelsResponse
from .types.query_devices_response import QueryDevicesResponse
from .types.query_software_inventory_response import QuerySoftwareInventoryResponse
from .types.software_inventory import SoftwareInventory

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AssetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAssetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAssetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAssetsClient
        """
        return self._raw_client

    def query_devices(
        self,
        *,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        filter: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        order: typing.Optional[str] = None,
        include_raw_data: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QueryDevicesResponse:
        """
        Query devices from an asset inventory system

        Parameters
        ----------
        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        limit : typing.Optional[int]
            Number of finding reports to return. Defaults to 50.

        cursor : typing.Optional[str]
            Start search from cursor position.

        filter : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter results by this query. For more information on filtering, refer to our [Filtering Guide](https://docs.synqly.com/guides/connectors/assets/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.

        order : typing.Optional[str]
            Select a field to order the results by. Defaults to `time`. To control the direction of the sorting, append
            `[asc]` or `[desc]` to the field name. For example, `time[asc]` will sort the results by `time` in ascending order.
            The ordering defaults to `asc` if not specified.

        include_raw_data : typing.Optional[bool]
            Include the raw data from the provider in the response. Defaults to `false`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryDevicesResponse

        Examples
        --------
        from synqly import SynqlyEngine

        client = SynqlyEngine(
            token="YOUR_TOKEN",
        )
        client.assets.query_devices()
        """
        _response = self._raw_client.query_devices(
            meta=meta,
            limit=limit,
            cursor=cursor,
            filter=filter,
            order=order,
            include_raw_data=include_raw_data,
            request_options=request_options,
        )
        return _response.data

    def create_asset(
        self,
        *,
        device: Device,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        source_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDeviceResponse:
        """
        Creates a `Device` object in the token-linked Integration.

        Parameters
        ----------
        device : Device

        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        source_name : typing.Optional[str]
            Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
            Omit or leave empty when the integration does not use it; some integrations require it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDeviceResponse

        Examples
        --------
        from synqly import SynqlyEngine
        from synqly.ocsf.v_1_3_0.inventoryinfo.classes import InventoryInfo
        from synqly.ocsf.v_1_3_0.objects import Device, Metadata, Product

        client = SynqlyEngine(
            token="YOUR_TOKEN",
        )
        client.assets.create_asset(
            device=InventoryInfo(
                activity_id=1,
                category_uid=1,
                class_uid=1,
                device=Device(
                    type_id=1,
                ),
                metadata=Metadata(
                    product=Product(),
                    version="version",
                ),
                severity_id=1,
                time=1,
                type_uid=1,
            ),
        )
        """
        _response = self._raw_client.create_asset(
            device=device, meta=meta, source_name=source_name, request_options=request_options
        )
        return _response.data

    def create_devices(
        self,
        *,
        devices: typing.Sequence[Device],
        source_name: str,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        custom_properties: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDevicesResponse:
        """
        Bulk create devices in an device inventory system

        Parameters
        ----------
        devices : typing.Sequence[Device]

        source_name : str
            Connector hint passed to the integration (for example ServiceNow discovery_source with Identify & Reconcile).

        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        custom_properties : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDevicesResponse

        Examples
        --------
        from synqly import SynqlyEngine
        from synqly.ocsf.v_1_3_0.inventoryinfo.classes import InventoryInfo
        from synqly.ocsf.v_1_3_0.objects import Device, Metadata, Product

        client = SynqlyEngine(
            token="YOUR_TOKEN",
        )
        client.assets.create_devices(
            devices=[
                InventoryInfo(
                    activity_id=1,
                    category_uid=1,
                    class_uid=1,
                    device=Device(
                        type_id=1,
                    ),
                    metadata=Metadata(
                        product=Product(),
                        version="version",
                    ),
                    severity_id=1,
                    time=1,
                    type_uid=1,
                ),
                InventoryInfo(
                    activity_id=1,
                    category_uid=1,
                    class_uid=1,
                    device=Device(
                        type_id=1,
                    ),
                    metadata=Metadata(
                        product=Product(),
                        version="version",
                    ),
                    severity_id=1,
                    time=1,
                    type_uid=1,
                ),
            ],
            source_name="source_name",
        )
        """
        _response = self._raw_client.create_devices(
            devices=devices,
            source_name=source_name,
            meta=meta,
            custom_properties=custom_properties,
            request_options=request_options,
        )
        return _response.data

    def get_labels(
        self,
        *,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetLabelsResponse:
        """
        Get labels from an asset inventory system

        Parameters
        ----------
        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetLabelsResponse

        Examples
        --------
        from synqly import SynqlyEngine

        client = SynqlyEngine(
            token="YOUR_TOKEN",
        )
        client.assets.get_labels()
        """
        _response = self._raw_client.get_labels(meta=meta, request_options=request_options)
        return _response.data

    def query_software(
        self,
        *,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        filter: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        order: typing.Optional[str] = None,
        include_raw_data: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QuerySoftwareInventoryResponse:
        """
        Query software inventory records from an asset management system

        Parameters
        ----------
        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        limit : typing.Optional[int]
            Number of software inventory records to return. Defaults to 50.

        cursor : typing.Optional[str]
            Start search from cursor position.

        filter : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter results by this query. For more information on filtering, refer to the [Assets Filtering Guide](https://docs.synqly.com/guides/connectors/assets/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.

        order : typing.Optional[str]
            Select a field to order the results by. Defaults to `package.name`. To control the direction of the sorting, append
            `[asc]` or `[desc]` to the field name. For example, `package.name[asc]` will sort the results by package name in ascending order.
            The ordering defaults to `asc` if not specified.

        include_raw_data : typing.Optional[bool]
            Include the raw data from the provider in the response. Defaults to `false`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuerySoftwareInventoryResponse

        Examples
        --------
        from synqly import SynqlyEngine

        client = SynqlyEngine(
            token="YOUR_TOKEN",
        )
        client.assets.query_software()
        """
        _response = self._raw_client.query_software(
            meta=meta,
            limit=limit,
            cursor=cursor,
            filter=filter,
            order=order,
            include_raw_data=include_raw_data,
            request_options=request_options,
        )
        return _response.data

    def create_software(
        self,
        *,
        software_inventory: SoftwareInventory,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        source_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSoftwareInventoryResponse:
        """
        Creates a software inventory record in the token-linked Integration.

        Parameters
        ----------
        software_inventory : SoftwareInventory

        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        source_name : typing.Optional[str]
            Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
            Omit or leave empty when the integration does not use it; some integrations require it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSoftwareInventoryResponse

        Examples
        --------
        from synqly import SynqlyEngine
        from synqly.ocsf.v_1_8_0.objects import Device, Metadata, Product
        from synqly.ocsf.v_1_8_0.softwareinventoryinfo.classes import SoftwareInfo

        client = SynqlyEngine(
            token="YOUR_TOKEN",
        )
        client.assets.create_software(
            software_inventory=SoftwareInfo(
                activity_id=1,
                category_uid=1,
                class_uid=1,
                device=Device(
                    type_id=1,
                ),
                metadata=Metadata(
                    product=Product(),
                    version="version",
                ),
                severity_id=1,
                time=1,
                type_uid=1,
            ),
        )
        """
        _response = self._raw_client.create_software(
            software_inventory=software_inventory, meta=meta, source_name=source_name, request_options=request_options
        )
        return _response.data


class AsyncAssetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAssetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAssetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAssetsClient
        """
        return self._raw_client

    async def query_devices(
        self,
        *,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        filter: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        order: typing.Optional[str] = None,
        include_raw_data: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QueryDevicesResponse:
        """
        Query devices from an asset inventory system

        Parameters
        ----------
        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        limit : typing.Optional[int]
            Number of finding reports to return. Defaults to 50.

        cursor : typing.Optional[str]
            Start search from cursor position.

        filter : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter results by this query. For more information on filtering, refer to our [Filtering Guide](https://docs.synqly.com/guides/connectors/assets/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.

        order : typing.Optional[str]
            Select a field to order the results by. Defaults to `time`. To control the direction of the sorting, append
            `[asc]` or `[desc]` to the field name. For example, `time[asc]` will sort the results by `time` in ascending order.
            The ordering defaults to `asc` if not specified.

        include_raw_data : typing.Optional[bool]
            Include the raw data from the provider in the response. Defaults to `false`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryDevicesResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyEngine

        client = AsyncSynqlyEngine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.assets.query_devices()


        asyncio.run(main())
        """
        _response = await self._raw_client.query_devices(
            meta=meta,
            limit=limit,
            cursor=cursor,
            filter=filter,
            order=order,
            include_raw_data=include_raw_data,
            request_options=request_options,
        )
        return _response.data

    async def create_asset(
        self,
        *,
        device: Device,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        source_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDeviceResponse:
        """
        Creates a `Device` object in the token-linked Integration.

        Parameters
        ----------
        device : Device

        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        source_name : typing.Optional[str]
            Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
            Omit or leave empty when the integration does not use it; some integrations require it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDeviceResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyEngine
        from synqly.ocsf.v_1_3_0.inventoryinfo.classes import InventoryInfo
        from synqly.ocsf.v_1_3_0.objects import Device, Metadata, Product

        client = AsyncSynqlyEngine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.assets.create_asset(
                device=InventoryInfo(
                    activity_id=1,
                    category_uid=1,
                    class_uid=1,
                    device=Device(
                        type_id=1,
                    ),
                    metadata=Metadata(
                        product=Product(),
                        version="version",
                    ),
                    severity_id=1,
                    time=1,
                    type_uid=1,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_asset(
            device=device, meta=meta, source_name=source_name, request_options=request_options
        )
        return _response.data

    async def create_devices(
        self,
        *,
        devices: typing.Sequence[Device],
        source_name: str,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        custom_properties: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateDevicesResponse:
        """
        Bulk create devices in an device inventory system

        Parameters
        ----------
        devices : typing.Sequence[Device]

        source_name : str
            Connector hint passed to the integration (for example ServiceNow discovery_source with Identify & Reconcile).

        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        custom_properties : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateDevicesResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyEngine
        from synqly.ocsf.v_1_3_0.inventoryinfo.classes import InventoryInfo
        from synqly.ocsf.v_1_3_0.objects import Device, Metadata, Product

        client = AsyncSynqlyEngine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.assets.create_devices(
                devices=[
                    InventoryInfo(
                        activity_id=1,
                        category_uid=1,
                        class_uid=1,
                        device=Device(
                            type_id=1,
                        ),
                        metadata=Metadata(
                            product=Product(),
                            version="version",
                        ),
                        severity_id=1,
                        time=1,
                        type_uid=1,
                    ),
                    InventoryInfo(
                        activity_id=1,
                        category_uid=1,
                        class_uid=1,
                        device=Device(
                            type_id=1,
                        ),
                        metadata=Metadata(
                            product=Product(),
                            version="version",
                        ),
                        severity_id=1,
                        time=1,
                        type_uid=1,
                    ),
                ],
                source_name="source_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_devices(
            devices=devices,
            source_name=source_name,
            meta=meta,
            custom_properties=custom_properties,
            request_options=request_options,
        )
        return _response.data

    async def get_labels(
        self,
        *,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetLabelsResponse:
        """
        Get labels from an asset inventory system

        Parameters
        ----------
        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetLabelsResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyEngine

        client = AsyncSynqlyEngine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.assets.get_labels()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_labels(meta=meta, request_options=request_options)
        return _response.data

    async def query_software(
        self,
        *,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        filter: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        order: typing.Optional[str] = None,
        include_raw_data: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QuerySoftwareInventoryResponse:
        """
        Query software inventory records from an asset management system

        Parameters
        ----------
        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        limit : typing.Optional[int]
            Number of software inventory records to return. Defaults to 50.

        cursor : typing.Optional[str]
            Start search from cursor position.

        filter : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter results by this query. For more information on filtering, refer to the [Assets Filtering Guide](https://docs.synqly.com/guides/connectors/assets/query-filters). Defaults to no filter. If used more than once, the queries are ANDed together.

        order : typing.Optional[str]
            Select a field to order the results by. Defaults to `package.name`. To control the direction of the sorting, append
            `[asc]` or `[desc]` to the field name. For example, `package.name[asc]` will sort the results by package name in ascending order.
            The ordering defaults to `asc` if not specified.

        include_raw_data : typing.Optional[bool]
            Include the raw data from the provider in the response. Defaults to `false`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuerySoftwareInventoryResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyEngine

        client = AsyncSynqlyEngine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.assets.query_software()


        asyncio.run(main())
        """
        _response = await self._raw_client.query_software(
            meta=meta,
            limit=limit,
            cursor=cursor,
            filter=filter,
            order=order,
            include_raw_data=include_raw_data,
            request_options=request_options,
        )
        return _response.data

    async def create_software(
        self,
        *,
        software_inventory: SoftwareInventory,
        meta: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        source_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSoftwareInventoryResponse:
        """
        Creates a software inventory record in the token-linked Integration.

        Parameters
        ----------
        software_inventory : SoftwareInventory

        meta : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Add metadata to the response by invoking meta functions. Documentation for [meta functions](https://docs.synqly.com/api-reference/meta-functions) is available. Not all meta functions are available at every endpoint.

        source_name : typing.Optional[str]
            Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
            Omit or leave empty when the integration does not use it; some integrations require it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSoftwareInventoryResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyEngine
        from synqly.ocsf.v_1_8_0.objects import Device, Metadata, Product
        from synqly.ocsf.v_1_8_0.softwareinventoryinfo.classes import SoftwareInfo

        client = AsyncSynqlyEngine(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.assets.create_software(
                software_inventory=SoftwareInfo(
                    activity_id=1,
                    category_uid=1,
                    class_uid=1,
                    device=Device(
                        type_id=1,
                    ),
                    metadata=Metadata(
                        product=Product(),
                        version="version",
                    ),
                    severity_id=1,
                    time=1,
                    type_uid=1,
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_software(
            software_inventory=software_inventory, meta=meta, source_name=source_name, request_options=request_options
        )
        return _response.data
