# This file was auto-generated by Fern from our API Definition.

ClassUid = int
"""
ClassUid is an enum, and the following values are allowed.
2005 - IncidentFinding: An Incident Finding reports the creation, update, or closure of security incidents as a result of detections and/or analytics.
"""
