# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..auth_base.types.change_password_response import ChangePasswordResponse
from ..auth_base.types.logon_response import LogonResponse
from ..auth_base.types.sso_configuration_id import SsoConfigurationId
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..organization_base.types.organization_id import OrganizationId
from .raw_client import AsyncRawAuthClient, RawAuthClient
from .types.create_sso_configuration import CreateSsoConfiguration
from .types.create_sso_response import CreateSsoResponse
from .types.get_sso_metadata_response import GetSsoMetadataResponse
from .types.get_sso_response import GetSsoResponse
from .types.list_sso_response import ListSsoResponse
from .types.update_sso_configuration import UpdateSsoConfiguration
from .types.update_sso_response import UpdateSsoResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AuthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAuthClient
        """
        return self._raw_client

    def logon(
        self,
        organization_id: OrganizationId,
        *,
        name: str,
        secret: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LogonResponse:
        """
        Initiates a new session for the given member in specified Synqly organization.

        Parameters
        ----------
        organization_id : OrganizationId

        name : str
            Email address identifying the member to initiate a session for.

        secret : str
            Password of the member to initiate a session for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LogonResponse
        """
        _response = self._raw_client.logon(organization_id, name=name, secret=secret, request_options=request_options)
        return _response.data

    def change_password(
        self, *, old_secret: str, new_secret: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ChangePasswordResponse:
        """
        Change member password.

        Parameters
        ----------
        old_secret : str
            Old member secret

        new_secret : str
            New member secret

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChangePasswordResponse
        """
        _response = self._raw_client.change_password(
            old_secret=old_secret, new_secret=new_secret, request_options=request_options
        )
        return _response.data

    def logoff(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Terminates the session identified by the given logon token.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None
        """
        _response = self._raw_client.logoff(request_options=request_options)
        return _response.data

    def create_sso(
        self, *, fullname: str, config: CreateSsoConfiguration, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateSsoResponse:
        """
        Configure an identity provider for Single Sign-On (SSO) with the organization.
        Returns the created resource with its assigned SSO configuration ID.

        Parameters
        ----------
        fullname : str
            Display name for the configuration, used on authentication screens.
            **Note:** To avoid confusion this name must be unique, however it cannot be used
            as an identifier in API calls.

        config : CreateSsoConfiguration
            Identity provider configuration. The type discriminator determines the SSO provider type.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSsoResponse
        """
        _response = self._raw_client.create_sso(fullname=fullname, config=config, request_options=request_options)
        return _response.data

    def list_sso(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListSsoResponse:
        """
        List all Single Sign-On (SSO) configurations for the organization.
        Client secrets are not included.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSsoResponse
        """
        _response = self._raw_client.list_sso(request_options=request_options)
        return _response.data

    def get_sso(
        self, sso_id: SsoConfigurationId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSsoResponse:
        """
        Retrieve a specific Single Sign-On (SSO) configuration. Client
        secrets are not included.

        Parameters
        ----------
        sso_id : SsoConfigurationId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoResponse
        """
        _response = self._raw_client.get_sso(sso_id, request_options=request_options)
        return _response.data

    def get_sso_metadata(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetSsoMetadataResponse:
        """
        Returns configuration that must be used when configuring Identity
        Providers, such as the OIDC redirect URI or SAML ACS URL and SP
        entity ID.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoMetadataResponse
        """
        _response = self._raw_client.get_sso_metadata(request_options=request_options)
        return _response.data

    def update_sso(
        self,
        sso_id: SsoConfigurationId,
        *,
        fullname: str,
        config: UpdateSsoConfiguration,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateSsoResponse:
        """
        Update the SSO configuration by ID. This is a full replacement of the
        configuration. The `updated_at` field is used for optimistic locking
        to prevent concurrent updates.

        Parameters
        ----------
        sso_id : SsoConfigurationId

        fullname : str
            Display name for the configuration, used on authentication screens.
            **Note:** To avoid confusion this name must be unique, however it cannot be used
            as an identifier in API calls.

        config : UpdateSsoConfiguration
            Identity provider configuration. The type discriminator determines the SSO provider type.

        updated_at : typing.Optional[dt.datetime]
            Used for optimistic locking to prevent concurrent updates.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateSsoResponse
        """
        _response = self._raw_client.update_sso(
            sso_id, fullname=fullname, config=config, updated_at=updated_at, request_options=request_options
        )
        return _response.data

    def delete_sso(
        self, sso_id: SsoConfigurationId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a specific Single Sign-On (SSO) configuration. This may disable signing on
        with the identity provider defined in the configuration, and can result in members
        linked to that identity provider no longer being able to access the Organization.

        Parameters
        ----------
        sso_id : SsoConfigurationId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None
        """
        _response = self._raw_client.delete_sso(sso_id, request_options=request_options)
        return _response.data


class AsyncAuthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAuthClient
        """
        return self._raw_client

    async def logon(
        self,
        organization_id: OrganizationId,
        *,
        name: str,
        secret: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LogonResponse:
        """
        Initiates a new session for the given member in specified Synqly organization.

        Parameters
        ----------
        organization_id : OrganizationId

        name : str
            Email address identifying the member to initiate a session for.

        secret : str
            Password of the member to initiate a session for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LogonResponse
        """
        _response = await self._raw_client.logon(
            organization_id, name=name, secret=secret, request_options=request_options
        )
        return _response.data

    async def change_password(
        self, *, old_secret: str, new_secret: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ChangePasswordResponse:
        """
        Change member password.

        Parameters
        ----------
        old_secret : str
            Old member secret

        new_secret : str
            New member secret

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ChangePasswordResponse
        """
        _response = await self._raw_client.change_password(
            old_secret=old_secret, new_secret=new_secret, request_options=request_options
        )
        return _response.data

    async def logoff(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Terminates the session identified by the given logon token.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None
        """
        _response = await self._raw_client.logoff(request_options=request_options)
        return _response.data

    async def create_sso(
        self, *, fullname: str, config: CreateSsoConfiguration, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateSsoResponse:
        """
        Configure an identity provider for Single Sign-On (SSO) with the organization.
        Returns the created resource with its assigned SSO configuration ID.

        Parameters
        ----------
        fullname : str
            Display name for the configuration, used on authentication screens.
            **Note:** To avoid confusion this name must be unique, however it cannot be used
            as an identifier in API calls.

        config : CreateSsoConfiguration
            Identity provider configuration. The type discriminator determines the SSO provider type.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSsoResponse
        """
        _response = await self._raw_client.create_sso(fullname=fullname, config=config, request_options=request_options)
        return _response.data

    async def list_sso(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListSsoResponse:
        """
        List all Single Sign-On (SSO) configurations for the organization.
        Client secrets are not included.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListSsoResponse
        """
        _response = await self._raw_client.list_sso(request_options=request_options)
        return _response.data

    async def get_sso(
        self, sso_id: SsoConfigurationId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSsoResponse:
        """
        Retrieve a specific Single Sign-On (SSO) configuration. Client
        secrets are not included.

        Parameters
        ----------
        sso_id : SsoConfigurationId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoResponse
        """
        _response = await self._raw_client.get_sso(sso_id, request_options=request_options)
        return _response.data

    async def get_sso_metadata(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetSsoMetadataResponse:
        """
        Returns configuration that must be used when configuring Identity
        Providers, such as the OIDC redirect URI or SAML ACS URL and SP
        entity ID.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSsoMetadataResponse
        """
        _response = await self._raw_client.get_sso_metadata(request_options=request_options)
        return _response.data

    async def update_sso(
        self,
        sso_id: SsoConfigurationId,
        *,
        fullname: str,
        config: UpdateSsoConfiguration,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateSsoResponse:
        """
        Update the SSO configuration by ID. This is a full replacement of the
        configuration. The `updated_at` field is used for optimistic locking
        to prevent concurrent updates.

        Parameters
        ----------
        sso_id : SsoConfigurationId

        fullname : str
            Display name for the configuration, used on authentication screens.
            **Note:** To avoid confusion this name must be unique, however it cannot be used
            as an identifier in API calls.

        config : UpdateSsoConfiguration
            Identity provider configuration. The type discriminator determines the SSO provider type.

        updated_at : typing.Optional[dt.datetime]
            Used for optimistic locking to prevent concurrent updates.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateSsoResponse
        """
        _response = await self._raw_client.update_sso(
            sso_id, fullname=fullname, config=config, updated_at=updated_at, request_options=request_options
        )
        return _response.data

    async def delete_sso(
        self, sso_id: SsoConfigurationId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a specific Single Sign-On (SSO) configuration. This may disable signing on
        with the identity provider defined in the configuration, and can result in members
        linked to that identity provider no longer being able to access the Organization.

        Parameters
        ----------
        sso_id : SsoConfigurationId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None
        """
        _response = await self._raw_client.delete_sso(sso_id, request_options=request_options)
        return _response.data
