# This file was auto-generated by Fern from our API Definition.

StateId = int
"""
StateId is an enum, and the following values are allowed.
0 - Unknown: The state is unknown.
1 - New: The finding is new and yet to be reviewed.
2 - InProgress: The finding is under review.
3 - Suppressed: The finding was reviewed, considered as a false positive and is now suppressed.
4 - Resolved: The finding was reviewed and remediated and is now considered resolved.
99 - Other: The state is not mapped. See the <code>state</code> attribute, which contains a data source specific value.
"""
