# This file was auto-generated by Fern from our API Definition.

from .mapping_base import MappingBase
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class Mapping(MappingBase):
    data: str = pydantic.Field()
    """
    transform to apply.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
