# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action_id import ActionId
    from .base import Base
    from .id import Id
    from .parameter_location import ParameterLocation
    from .patch_op import PatchOp
    from .patch_operation import PatchOperation
    from .problem import Problem
    from .problem_cause import ProblemCause
    from .problem_context import ProblemContext
    from .problem_details import ProblemDetails
    from .problem_relation import ProblemRelation
    from .problem_type import ProblemType
    from .problematic_parameter import ProblematicParameter
    from .resource_id import ResourceId
    from .resource_reference import ResourceReference
    from .resource_type import ResourceType
_dynamic_imports: typing.Dict[str, str] = {
    "ActionId": ".action_id",
    "Base": ".base",
    "Id": ".id",
    "ParameterLocation": ".parameter_location",
    "PatchOp": ".patch_op",
    "PatchOperation": ".patch_operation",
    "Problem": ".problem",
    "ProblemCause": ".problem_cause",
    "ProblemContext": ".problem_context",
    "ProblemDetails": ".problem_details",
    "ProblemRelation": ".problem_relation",
    "ProblemType": ".problem_type",
    "ProblematicParameter": ".problematic_parameter",
    "ResourceId": ".resource_id",
    "ResourceReference": ".resource_reference",
    "ResourceType": ".resource_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActionId",
    "Base",
    "Id",
    "ParameterLocation",
    "PatchOp",
    "PatchOperation",
    "Problem",
    "ProblemCause",
    "ProblemContext",
    "ProblemDetails",
    "ProblemRelation",
    "ProblemType",
    "ProblematicParameter",
    "ResourceId",
    "ResourceReference",
    "ResourceType",
]
