# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..providers_generated.types.provider_config_id import ProviderConfigId
from .raw_client import AsyncRawCapabilitiesClient, RawCapabilitiesClient
from .types.get_provider_capabilities_expand_options import GetProviderCapabilitiesExpandOptions
from .types.list_connector_capabilities_expand_options import ListConnectorCapabilitiesExpandOptions
from .types.list_connectors_capabilities_response import ListConnectorsCapabilitiesResponse
from .types.list_provider_capabilities_expand_options import ListProviderCapabilitiesExpandOptions
from .types.list_providers_capabilities_response import ListProvidersCapabilitiesResponse
from .types.provider_capabilities_response import ProviderCapabilitiesResponse


class CapabilitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCapabilitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCapabilitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCapabilitiesClient
        """
        return self._raw_client

    def list_connectors(
        self,
        *,
        expand: typing.Optional[
            typing.Union[
                ListConnectorCapabilitiesExpandOptions, typing.Sequence[ListConnectorCapabilitiesExpandOptions]
            ]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConnectorsCapabilitiesResponse:
        """
        Returns a list of all `Connectors`.

        Parameters
        ----------
        expand : typing.Optional[typing.Union[ListConnectorCapabilitiesExpandOptions, typing.Sequence[ListConnectorCapabilitiesExpandOptions]]]
            Expand the capabilities result fields that are otherwise
            omitted or returned as references to OpenAPI spec components.
            NOTE: This can yield very big response objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConnectorsCapabilitiesResponse

        Examples
        --------
        from synqly import SynqlyManagement

        client = SynqlyManagement(
            token="YOUR_TOKEN",
        )
        client.capabilities.list_connectors()
        """
        _response = self._raw_client.list_connectors(expand=expand, request_options=request_options)
        return _response.data

    def list_providers(
        self,
        *,
        expand: typing.Optional[
            typing.Union[ListProviderCapabilitiesExpandOptions, typing.Sequence[ListProviderCapabilitiesExpandOptions]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListProvidersCapabilitiesResponse:
        """
        Returns a list of all Provider capabilities and their configurations.

        Parameters
        ----------
        expand : typing.Optional[typing.Union[ListProviderCapabilitiesExpandOptions, typing.Sequence[ListProviderCapabilitiesExpandOptions]]]
            Expand the capabilities result fields that are otherwise
            omitted or returned as references to OpenAPI spec components.
            NOTE: This can yield very big response objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListProvidersCapabilitiesResponse

        Examples
        --------
        from synqly import SynqlyManagement

        client = SynqlyManagement(
            token="YOUR_TOKEN",
        )
        client.capabilities.list_providers()
        """
        _response = self._raw_client.list_providers(expand=expand, request_options=request_options)
        return _response.data

    def get_provider(
        self,
        provider_id: ProviderConfigId,
        *,
        expand: typing.Optional[
            typing.Union[GetProviderCapabilitiesExpandOptions, typing.Sequence[GetProviderCapabilitiesExpandOptions]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProviderCapabilitiesResponse:
        """
        Returns the capabilities and configurations for a specific Provider type

        Parameters
        ----------
        provider_id : ProviderConfigId

        expand : typing.Optional[typing.Union[GetProviderCapabilitiesExpandOptions, typing.Sequence[GetProviderCapabilitiesExpandOptions]]]
            Expand the capabilities result fields that are otherwise
            omitted or returned as references to OpenAPI spec components.
            NOTE: This can yield very big response objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderCapabilitiesResponse

        Examples
        --------
        from synqly import SynqlyManagement
        from synqly.providers_generated import ProviderConfigId

        client = SynqlyManagement(
            token="YOUR_TOKEN",
        )
        client.capabilities.get_provider(
            provider_id=ProviderConfigId.APPSEC_AMAZON_INSPECTOR,
        )
        """
        _response = self._raw_client.get_provider(provider_id, expand=expand, request_options=request_options)
        return _response.data


class AsyncCapabilitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCapabilitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCapabilitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCapabilitiesClient
        """
        return self._raw_client

    async def list_connectors(
        self,
        *,
        expand: typing.Optional[
            typing.Union[
                ListConnectorCapabilitiesExpandOptions, typing.Sequence[ListConnectorCapabilitiesExpandOptions]
            ]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListConnectorsCapabilitiesResponse:
        """
        Returns a list of all `Connectors`.

        Parameters
        ----------
        expand : typing.Optional[typing.Union[ListConnectorCapabilitiesExpandOptions, typing.Sequence[ListConnectorCapabilitiesExpandOptions]]]
            Expand the capabilities result fields that are otherwise
            omitted or returned as references to OpenAPI spec components.
            NOTE: This can yield very big response objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConnectorsCapabilitiesResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyManagement

        client = AsyncSynqlyManagement(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.capabilities.list_connectors()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_connectors(expand=expand, request_options=request_options)
        return _response.data

    async def list_providers(
        self,
        *,
        expand: typing.Optional[
            typing.Union[ListProviderCapabilitiesExpandOptions, typing.Sequence[ListProviderCapabilitiesExpandOptions]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListProvidersCapabilitiesResponse:
        """
        Returns a list of all Provider capabilities and their configurations.

        Parameters
        ----------
        expand : typing.Optional[typing.Union[ListProviderCapabilitiesExpandOptions, typing.Sequence[ListProviderCapabilitiesExpandOptions]]]
            Expand the capabilities result fields that are otherwise
            omitted or returned as references to OpenAPI spec components.
            NOTE: This can yield very big response objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListProvidersCapabilitiesResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyManagement

        client = AsyncSynqlyManagement(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.capabilities.list_providers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_providers(expand=expand, request_options=request_options)
        return _response.data

    async def get_provider(
        self,
        provider_id: ProviderConfigId,
        *,
        expand: typing.Optional[
            typing.Union[GetProviderCapabilitiesExpandOptions, typing.Sequence[GetProviderCapabilitiesExpandOptions]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProviderCapabilitiesResponse:
        """
        Returns the capabilities and configurations for a specific Provider type

        Parameters
        ----------
        provider_id : ProviderConfigId

        expand : typing.Optional[typing.Union[GetProviderCapabilitiesExpandOptions, typing.Sequence[GetProviderCapabilitiesExpandOptions]]]
            Expand the capabilities result fields that are otherwise
            omitted or returned as references to OpenAPI spec components.
            NOTE: This can yield very big response objects.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProviderCapabilitiesResponse

        Examples
        --------
        import asyncio

        from synqly import AsyncSynqlyManagement
        from synqly.providers_generated import ProviderConfigId

        client = AsyncSynqlyManagement(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.capabilities.get_provider(
                provider_id=ProviderConfigId.APPSEC_AMAZON_INSPECTOR,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_provider(provider_id, expand=expand, request_options=request_options)
        return _response.data
