# This file was auto-generated by Fern from our API Definition.

import typing

WebhookEvent = typing.Union[
    typing.Literal["TicketCreated", "TicketUpdated", "TicketDeleted", "TicketCommentCreated", "TicketCommentDeleted"],
    typing.Any,
]
