# This file was auto-generated by Fern from our API Definition.

ActivityId = int
"""
ActivityId is an enum, and the following values are allowed.
0 - Unknown: The event activity is unknown.
1 - Send
2 - Receive
3 - Scan: Email being scanned (example: security scanning)
4 - Trace: Follow an email message as it travels through an organization. The <code>message_trace_uid</code> should be populated when selected.
5 - MTARelay: Email processed by an MTA, typically combining send, receive, and scan operations into a single activity.
99 - Other: The event activity is not mapped. See the <code>activity_name</code> attribute, which contains a data source specific value.
"""
