# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .service_now_credential import ServiceNowCredential
import pydantic
import typing
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AppSecServiceNow(UncheckedBaseModel):
    """
    Configuration for ServiceNow Application Vulnerability Response (AVR) as an application security provider.

    [Configuration guide](https://docs.synqly.com/guides/provider-configuration/appsec-servicenow-setup)
    """

    credential: ServiceNowCredential = pydantic.Field()
    """
    Credentials used to access ServiceNow AVR.
    """

    oauth_scopes: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional scopes to request when authenticating with OAuth 2.0 client credentials. Leave empty when the ServiceNow Application Registry is set to `Broadly scoped` (recommended), which grants access based on the Application User's roles. Only set this when the registry is configured as `Securely scoped` and a specific Auth Scope is required.
    """

    url: str = pydantic.Field()
    """
    HTTPS base URL for the ServiceNow API.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
