# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .claroty_credential import ClarotyCredential
from .claroty_apiurl import ClarotyApiurl
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AssetsClarotyXdome(UncheckedBaseModel):
    """
    Configuration for the Claroty xDome Assets Provider

    [Configuration guide](https://docs.synqly.com/guides/provider-configuration/claroty-asset-setup)
    """

    credential: ClarotyCredential
    url: ClarotyApiurl = pydantic.Field()
    """
    Base URL for the Claroty xDome API.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
