# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .qualys_cloud_credential import QualysCloudCredential
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AssetsQualysCloud(UncheckedBaseModel):
    """
    Configuration for Qualys Cloud Platform as an Assets Provider
    """

    credential: QualysCloudCredential
    url: str = pydantic.Field()
    """
    URL for the Qualys Cloud API. This should be the base URL for the API, without any path components.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
