# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .copilot_chat_credential import CopilotChatCredential
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ChatMicrosoftCopilot(UncheckedBaseModel):
    """
    Configuration for Microsoft 365 Copilot.

    [Configuration guide](https://docs.synqly.com/guides/provider-configuration/microsoft-copilot-chat-setup)
    """

    credential: CopilotChatCredential
    tenant_id: str = pydantic.Field()
    """
    Azure Directory tenant identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
