# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .wiz_credential import WizCredential
from .wiz_region import WizRegion


class CloudSecurityWiz(UncheckedBaseModel):
    """
    Configuration for the Wiz Cloud Security Provider
    """

    api_endpoint_url: str = pydantic.Field()
    """
    Wiz GraphQL API endpoint URL. Copy this from the Wiz tenant's **API Endpoint URL** field.
    """

    credential: WizCredential
    region: WizRegion = pydantic.Field()
    """
    Region/deployment used to determine the Wiz OAuth token endpoint.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
