# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .trellix_ens_api_key_credential import TrellixEnsApiKeyCredential
import pydantic
from .trellix_ens_credential import TrellixEnsCredential
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class EdrTrellixEns(UncheckedBaseModel):
    """
    Configuration for Trellix Endpoint Security (ENS) via ePolicy Orchestrator. Use this provider for tenants running Trellix ENS rather than the Trellix EDR product.
    """

    api_key: TrellixEnsApiKeyCredential = pydantic.Field()
    """
    Tenant-scoped Trellix API key.
    """

    credential: TrellixEnsCredential = pydantic.Field()
    """
    OAuth client credentials for a Trellix IAM client.
    """

    tenant_id: str = pydantic.Field()
    """
    Trellix tenant GUID for the customer tenancy you want to query.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
