# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .okta_credential import OktaCredential
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class IdentityOkta(UncheckedBaseModel):
    """
    Configuration for Okta Identity.

    [Configuration guide](https://docs.synqly.com/guides/provider-configuration/okta-identity-setup)
    """

    credential: OktaCredential
    url: str = pydantic.Field()
    """
    Base URL for the Okta API.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
