# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .azure_dev_ops_ticketing_credential import AzureDevOpsTicketingCredential


class TicketingAzureDevOps(UncheckedBaseModel):
    """
    Configuration for Azure DevOps Boards.

    [Configuration guide](https://docs.synqly.com/guides/provider-configuration/azuredevops-ticketing-setup)
    """

    credential: AzureDevOpsTicketingCredential
    default_issue_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Default work item type for ticket creation (e.g., "Issue", "Task", "Bug"). If provided, the issue_type field becomes optional in ticket creation requests.
    """

    organization: str = pydantic.Field()
    """
    Azure DevOps organization name.
    """

    project: str = pydantic.Field()
    """
    Azure DevOps project name. Used as the default project scope for work item queries.
    """

    url: str = pydantic.Field()
    """
    Base URL for the Azure DevOps API.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
