# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .git_hub_credential import GitHubCredential
import pydantic
import typing
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class TicketingGitHub(UncheckedBaseModel):
    """
    Configuration for GitHub Issues as a ticketing provider.
    """

    credential: GitHubCredential = pydantic.Field()
    """
    Fine-grained Personal Access Token with Issues Read and Write permission.
    """

    repository: str = pydantic.Field()
    """
    Target repository in owner/repo format. All issue operations are scoped to this repository.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Base URL for the GitHub environment. Only necessary with GitHub Enterprise Server deployments.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
