# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .vulnerabilities_axonius_dataset import VulnerabilitiesAxoniusDataset
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class VulnerabilitiesAxoniusMock(UncheckedBaseModel):
    """
    Configuration for a mocked Axonius as a Vulnerabilities Provider
    """

    dataset: VulnerabilitiesAxoniusDataset

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
