# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .horizon_3_credential import Horizon3Credential
from .horizon_3_region import Horizon3Region


class VulnerabilitiesHorizon3(UncheckedBaseModel):
    """
    Configuration for Horizon3 NodeZero as a Vulnerabilities Provider

    [Configuration guide](https://docs.synqly.com/guides/provider-configuration/horizon3-nodezero-vulnerabilities-setup)
    """

    credential: Horizon3Credential = pydantic.Field()
    """
    Credentials for the Horizon3 NodeZero GraphQL API.
    """

    region: Horizon3Region = pydantic.Field()
    """
    Region of the Horizon3 Portal.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
