# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2
from .....core.unchecked_base_model import UncheckedBaseModel


class ClassifierDetails(UncheckedBaseModel):
    """
    The Classifier Details object describes details about the classifier used for data classification.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the classifier.
    """

    type: str = pydantic.Field()
    """
    The type of the classifier.
    """

    uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the classifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
