# This file was auto-generated by Fern from our API Definition.

ManagedEntityTypeId = int
"""
ManagedEntityTypeId is an enum, and the following values are allowed.
0 - Unknown: The type is unknown.
1 - Device: A managed Device entity.  This item corresponds to population of the <code>device</code> attribute.
2 - User: A managed User entity.  This item corresponds to population of the <code>user</code> attribute.
3 - Group: A managed Group entity.  This item corresponds to population of the <code>group</code> attribute.
4 - Organization: A managed Organization entity.  This item corresponds to population of the <code>org</code> attribute.
5 - Policy: A managed Policy entity.  This item corresponds to population of the <code>policy</code> attribute.
6 - Email: A managed Email entity.  This item corresponds to population of the <code>email</code> attribute.
7 - NetworkZone: A managed Network Zone entity. Populate the <code>name</code> attribute with the zone name and/or the <code>uid</code> attribute with the zone ID. Additional zone information can be added to the <code>data</code> attribute.
99 - Other: The type is not mapped. See the <code>type</code> attribute, which contains a data source specific value.
"""
