# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from .....core.unchecked_base_model import UncheckedBaseModel
from .application import Application
from .message_context_ai_role_id import MessageContextAiRoleId
from .service import Service


class MessageContext(UncheckedBaseModel):
    """
    Communication context for AI system interactions including protocols, roles, clients, and session information for MCP and other AI communication systems.
    """

    ai_role: typing.Optional[str] = pydantic.Field(default=None)
    """
    The normalized caption of the <code>ai_role_id</code>.
    """

    ai_role_id: typing.Optional[MessageContextAiRoleId] = pydantic.Field(default=None)
    """
    Specifies the functional role of the AI within the context of this message, such as retrieving information, assisting reasoning, executing a tool, or generating content.
    """

    application: typing.Optional[Application] = pydantic.Field(default=None)
    """
    The initiating client application. In AI systems, this represents the client-side application or framework that initiates requests (e.g., LangChain application, web browser, mobile app, SDK implementation).
    """

    completion_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens in the model's response/completion for this message.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name or identifier of the message context. In AI systems, this could be the conversation ID, session name, thread identifier, or interaction name (e.g., 'user-session-123', 'conversation-abc', 'chat-thread-456').
    """

    prompt_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens in the input prompt for this message.
    """

    service: typing.Optional[Service] = pydantic.Field(default=None)
    """
    The server or service handling the request. In AI systems, this represents the AI service, API endpoint, or agent that processes and responds to requests (e.g., OpenAI API service, Claude API service, internal AI model service).
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of tokens used for this message (prompt + completion).
    """

    uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the message context. This could be a session ID, conversation ID, or other unique identifier that allows correlation of messages within the same context.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(MessageContext)
