# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .compliance_finding import ComplianceFinding
    from .device_action_request import DeviceActionRequest
    from .device_action_response import DeviceActionResponse
    from .endpoint_management_device import EndpointManagementDevice
    from .get_endpoint_management_device_response import GetEndpointManagementDeviceResponse
    from .query_device_applications_response import QueryDeviceApplicationsResponse
    from .query_device_compliance_response import QueryDeviceComplianceResponse
    from .query_endpoint_management_devices_response import QueryEndpointManagementDevicesResponse
    from .remediate_device_response import RemediateDeviceResponse
    from .remediation_request import RemediationRequest
_dynamic_imports: typing.Dict[str, str] = {
    "ComplianceFinding": ".compliance_finding",
    "DeviceActionRequest": ".device_action_request",
    "DeviceActionResponse": ".device_action_response",
    "EndpointManagementDevice": ".endpoint_management_device",
    "GetEndpointManagementDeviceResponse": ".get_endpoint_management_device_response",
    "QueryDeviceApplicationsResponse": ".query_device_applications_response",
    "QueryDeviceComplianceResponse": ".query_device_compliance_response",
    "QueryEndpointManagementDevicesResponse": ".query_endpoint_management_devices_response",
    "RemediateDeviceResponse": ".remediate_device_response",
    "RemediationRequest": ".remediation_request",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ComplianceFinding",
    "DeviceActionRequest",
    "DeviceActionResponse",
    "EndpointManagementDevice",
    "GetEndpointManagementDeviceResponse",
    "QueryDeviceApplicationsResponse",
    "QueryDeviceComplianceResponse",
    "QueryEndpointManagementDevicesResponse",
    "RemediateDeviceResponse",
    "RemediationRequest",
]
