# This file was auto-generated by Fern from our API Definition.

import typing

IndicatorTypeOv = typing.Union[
    typing.Literal[
        "anomalous_activity", "anonymization", "benign", "compromised", "malicious_activity", "attribution", "unknown"
    ],
    typing.Any,
]
