# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_integration_web_hook_request import CreateIntegrationWebHookRequest
    from .create_integration_web_hook_response import CreateIntegrationWebHookResponse
    from .integration_web_hook import IntegrationWebHook
    from .integration_web_hook_id import IntegrationWebHookId
    from .list_integration_web_hooks_response import ListIntegrationWebHooksResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateIntegrationWebHookRequest": ".create_integration_web_hook_request",
    "CreateIntegrationWebHookResponse": ".create_integration_web_hook_response",
    "IntegrationWebHook": ".integration_web_hook",
    "IntegrationWebHookId": ".integration_web_hook_id",
    "ListIntegrationWebHooksResponse": ".list_integration_web_hooks_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateIntegrationWebHookRequest",
    "CreateIntegrationWebHookResponse",
    "IntegrationWebHook",
    "IntegrationWebHookId",
    "ListIntegrationWebHooksResponse",
]
