# This file was auto-generated by Fern from our API Definition.

DnsQueryOpcodeId = int
"""
DnsQueryOpcodeId is an enum, and the following values are allowed.
0 - Query: Standard query
1 - InverseQuery: Inverse query, obsolete
2 - Status: Server status request
3 - Reserved: Reserved, not used
4 - Notify: Zone change notification
5 - Update: Dynamic DNS update
6 - DSOMessage: DNS Stateful Operations (DSO)
99 - Other: The DNS Opcode is not defined by the RFC. See the <code>opcode</code> attribute, which contains a data source specific value.
"""
