# This file was auto-generated by Fern from our API Definition.

LdapPersonEmploymentStatusId = int
"""
LdapPersonEmploymentStatusId is an enum, and the following values are allowed.
0 - Unknown: The employment status is unknown.
1 - Applicant: The user is a job applicant or candidate who has not yet been hired.
2 - Active: The user is currently employed and actively working.
3 - Terminated: The user's employment has been terminated.
4 - Retired: The user has retired from the organization.
99 - Other: The employment status is not mapped. See the <code>employment_status</code> attribute, which contains a data source specific value.
"""
