# This file was auto-generated by Fern from our API Definition.

SecurityStateStateId = int
"""
SecurityStateStateId is an enum, and the following values are allowed.
0 - Unknown: The security state is unknown.
1 - Missingoroutdatedcontent: The content is missing or outdated.
2 - Policymismatch: Not in compliance with the expected security policy.
3 - Innetworkquarantine: Isolated from the network.
4 - Protectionoff: Not protected by a security solution.
5 - Protectionmalfunction: The security solution is not functioning properly.
6 - Protectionnotlicensed: The security solution does not have a valid license.
7 - Unremediatedthreat: A detected threat has not been remediated.
8 - Suspiciousreputation: Reputation of the entity is suspicious.
9 - Rebootpending: A reboot is required for one or more pending actions.
10 - Contentislocked: The content is locked to a specific version.
11 - Notinstalled: The entity is not installed.
12 - Writablesystempartition: The system partition is writeable.
13 - SafetyNetfailure: The device has failed the SafetyNet check.
14 - Failedbootverify: The device has failed the boot verification process.
15 - Modifiedexecutionenvironment: The execution environment has been modified.
16 - SELinuxdisabled: The SELinux security feature has been disabled.
17 - Elevatedprivilegeshell: An elevated privilege shell has been detected.
18 - iOSfilesystemaltered: The file system has been altered on an iOS device.
19 - Openremoteaccess: Remote access is enabled.
20 - OTAupdatesdisabled: Mobile OTA (Over The Air) updates have been disabled.
21 - Rooted: The device has been modified to allow root access.
22 - Androidpartitionmodified: The Android partition has been modified.
23 - Compliancefailure: The entity is not compliant with the associated security policy.
99 - Other: The security state is not mapped. See the <code>state</code> attribute, which contains data source specific values.
"""
