# This file was auto-generated by Fern from our API Definition.

RcodeId = int
"""
RcodeId is an enum, and the following values are allowed.
0 - NoError: No Error.
1 - FormError: Format Error.
2 - ServError: Server Failure.
3 - NXDomain: Non-Existent Domain.
4 - NotImp: Not Implemented.
5 - Refused: Query Refused.
6 - YXDomain: Name Exists when it should not.
7 - YXRRSet: RR Set Exists when it should not.
8 - NXRRSet: RR Set that should exist does not.
9 - NotAuth: Not Authorized or Server Not Authoritative for zone.
10 - NotZone: Name not contained in zone.
11 - DSOTYPENI: DSO-TYPE Not Implemented.
16 - VERS: TSIG Signature Failure or Bad OPT Version.
17 - BADKEY: Key not recognized.
18 - BADTIME: Signature out of time window.
19 - BADMODE: Bad TKEY Mode.
20 - BADNAME: Duplicate key name.
21 - BADALG: Algorithm not supported.
22 - BADTRUNC: Bad Truncation.
23 - BADCOOKIE: Bad/missing Server Cookie.
24 - Unassigned: The codes deemed to be unassigned by the RFC (unassigned codes: 12-15, 24-3840, 4096-65534).
25 - Reserved: The codes deemed to be reserved by the RFC (codes: 3841-4095, 65535).
99 - Other: The dns response code is not defined by the RFC.
"""
