# This file was auto-generated by Fern from our API Definition.

import typing

TokensActions = typing.Union[
    typing.Literal[
        "list",
        "create",
        "create_integration",
        "create_synqly_integrations",
        "delete",
        "get",
        "reset",
        "refresh",
        "remove_secondary",
        "*",
    ],
    typing.Any,
]
