# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ...core.unchecked_base_model import UncheckedBaseModel
from .software_inventory import SoftwareInventory


class CreateSoftwareInventoryRequest(UncheckedBaseModel):
    software_inventory: SoftwareInventory
    source_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional connector hint (for example ServiceNow discovery_source with Identify & Reconcile).
    Omit or leave empty when the integration does not use it; some integrations require it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(CreateSoftwareInventoryRequest)
