# This file was auto-generated by Fern from our API Definition.

ClassUid = int
"""
ClassUid is an enum, and the following values are allowed.
6004 - WebResourceAccessActivity: Web Resource Access Activity events describe successful/failed attempts to access a web resource over HTTP.
"""
