# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .account import Account
    from .create_account_request import CreateAccountRequest
    from .create_account_response import CreateAccountResponse
    from .create_account_response_result import CreateAccountResponseResult
    from .get_account_response import GetAccountResponse
    from .list_accounts_response import ListAccountsResponse
    from .patch_account_response import PatchAccountResponse
    from .update_account_request import UpdateAccountRequest
    from .update_account_response import UpdateAccountResponse
_dynamic_imports: typing.Dict[str, str] = {
    "Account": ".account",
    "CreateAccountRequest": ".create_account_request",
    "CreateAccountResponse": ".create_account_response",
    "CreateAccountResponseResult": ".create_account_response_result",
    "GetAccountResponse": ".get_account_response",
    "ListAccountsResponse": ".list_accounts_response",
    "PatchAccountResponse": ".patch_account_response",
    "UpdateAccountRequest": ".update_account_request",
    "UpdateAccountResponse": ".update_account_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Account",
    "CreateAccountRequest",
    "CreateAccountResponse",
    "CreateAccountResponseResult",
    "GetAccountResponse",
    "ListAccountsResponse",
    "PatchAccountResponse",
    "UpdateAccountRequest",
    "UpdateAccountResponse",
]
