# This file was auto-generated by Fern from our API Definition.

DatabaseTypeId = int
"""
DatabaseTypeId is an enum, and the following values are allowed.
0 - Unknown: The type is unknown.
1 - Relational
2 - Network
3 - ObjectOriented
4 - Centralized
5 - Operational
6 - NoSQL
99 - Other: The type is not mapped. See the <code>type</code> attribute, which contains a data source specific value.
"""
