# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2
from .....core.unchecked_base_model import UncheckedBaseModel
from ...base.types.timestamp import Timestamp


class QueryInfo(UncheckedBaseModel):
    """
    The query info object holds information related to data access within a datastore. To access, manipulate, delete, or retrieve data from a datastore, a query must be written using a specific syntax.
    """

    bytes: typing.Optional[int] = pydantic.Field(default=None)
    """
    The size of the data returned from the query.
    """

    data: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The data returned from the query execution.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The query name for a saved or scheduled query.
    """

    query_string: str = pydantic.Field()
    """
    A string representing the query code being run. For example: <code>SELECT * FROM my_table</code>
    """

    query_time: typing.Optional[Timestamp] = pydantic.Field(default=None)
    """
    The time when the query was run.
    """

    query_time_dt: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The time when the query was run.
    """

    uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the query.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
