# This file was auto-generated by Fern from our API Definition.

import typing

from ...core import enum

T_Result = typing.TypeVar("T_Result")


class IoaRuleType(enum.StrEnum):
    """
    The kind of endpoint activity an IOA rule matches on.
    """

    PROCESS_CREATION = "process_creation"
    FILE_CREATION = "file_creation"
    NETWORK_CONNECTION = "network_connection"
    DOMAIN_NAME = "domain_name"
    _UNKNOWN = "__IOARULETYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "IoaRuleType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        process_creation: typing.Callable[[], T_Result],
        file_creation: typing.Callable[[], T_Result],
        network_connection: typing.Callable[[], T_Result],
        domain_name: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is IoaRuleType.PROCESS_CREATION:
            return process_creation()
        if self is IoaRuleType.FILE_CREATION:
            return file_creation()
        if self is IoaRuleType.NETWORK_CONNECTION:
            return network_connection()
        if self is IoaRuleType.DOMAIN_NAME:
            return domain_name()
        return _unknown_member(self._value_)
