# This file was auto-generated by Fern from our API Definition.

ActivityId = int
"""
ActivityId is an enum, and the following values are allowed.
0 - Unknown: The event activity is unknown.
1 - Clear: Clear the event log database, file, or cache.
2 - Delete: Delete the event log database, file, or cache.
3 - Export: Export the event log database, file, or cache.
4 - Archive: Archive the event log database, file, or cache.
5 - Rotate: Rotate the event log database, file, or cache.
6 - Start: Start the event logging service.
7 - Stop: Stop the event logging service.
8 - Restart: Restart the event logging service.
9 - Enable: Enable the event logging service.
10 - Disable: Disable the event logging service.
99 - Other: The event activity is not mapped. See the <code>activity_name</code> attribute, which contains a data source specific value.
"""
