# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
from .sso_user_configuration import SsoUserConfiguration
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class GetSsoMetadataResponse(UncheckedBaseModel):
    result: SsoUserConfiguration = pydantic.Field()
    """
    Information the user needs to configure their Identity Provider.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
