# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...auth_base.types.sso_configuration import SsoConfiguration
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class ListSsoResponse(UncheckedBaseModel):
    result: typing.List[SsoConfiguration]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
