# This file was auto-generated by Fern from our API Definition.

from ...core.unchecked_base_model import UncheckedBaseModel
import typing
from .organization_webhook import OrganizationWebhook
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ListOrganizationWebhooksResponse(UncheckedBaseModel):
    result: typing.List[OrganizationWebhook] = pydantic.Field()
    """
    List of webhooks for the organization.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow"
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
