# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...common.types.base import Base
from ...core.datetime_utils import serialize_datetime
from ...core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from ...credentials.types.credential_id import CredentialId
from ...organization_base.types.environment import Environment
from ...organization_webhook_base.types.webhook_filter import WebhookFilter
from ...organization_webhook_base.types.webhook_id import WebhookId


class OrganizationWebhook(Base):
    id: WebhookId
    fullname: str = pydantic_v1.Field()
    """
    Human friendly slug for this webhook
    """

    environment: Environment = pydantic_v1.Field()
    """
    Environment that the webhook is configured for. Only events associated with this environment will trigger the webhook.
    """

    filters: typing.List[WebhookFilter] = pydantic_v1.Field()
    """
    Specifies which Webhooks to send.
    """

    url: str = pydantic_v1.Field()
    """
    URL that webhooks will be sent to
    """

    credential_id: CredentialId = pydantic_v1.Field()
    """
    Credential contain secret
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
